apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: management
  # namespace: example-sriov
spec:
  #Change this to match the CNI config file name in your environment
  NetworkID: flannel
  NetworkType: flannel
---
apiVersion: danm.k8s.io/v1
kind: DanmNet
metadata:
  name: sriov-a
  # namespace: example-sriov
spec:
  NetworkID: sriov-a
  NetworkType: sriov
  Options:
    #Change this to the name of a valid SR-IOV Device Pool in your cluster
    device_pool: "mellanox.com/mlx5_vf"
    container_prefix: first_path
    rt_tables: 250
    #Don't forget to change this to match your switch config!
    vlan: 250
    cidr: 10.100.20.0/24
    allocation_pool:
      start: 10.100.20.10
      end: 10.100.20.30
